server:
  port: 8080
spring:
  application:
    name: account
  jersey:
    type: filter
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        format_sql: true
    show-sql: false
  datasource:
    url: jdbc:oracle:thin:@obaasdevdb_tp?TNS_ADMIN=/Users/pparkins/Downloads/Wallet_OBAASDEVDB
    username: account
    password: Welcome1234##
    driver-class-name: oracle.jdbc.OracleDriver
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
      connection-pool-name: TransactionConnectionPool
      initial-pool-size: 15
      min-pool-size: 10
      max-pool-size: 30
lra:
  coordinator:
    url: http://otmm-tcs.otmm.svc.cluster.local:9000/api/v1/lra-coordinator
