apiVersion: v1
kind: Service
metadata:
  name: transfer
  labels:
    app: transfer
    service: transfer
spec:
  ports:
    - port: 8080
      name: http
      targetPort: 8080
  selector:
    app: transfer