server:
  port: 8081
  host: 0.0.0.0

mp.lra:
  coordinator.url: http://localhost:9000/api/v1/lra-coordinator
  propagation.active: true
  participant.url: http://localhost:8081
  coordinator.headers-propagation.prefix: ["x-b3-", "oracle-tmm-", "authorization", "refresh-"]

deposit:
  account:
    service:
      url: http://account.application:8080/deposit
withdraw:
  account:
    service:
      url: http://account.application:8080/withdraw