server:
  port: 8080
account:
  deposit:
      url: http://account.application:8080/deposit/deposit
  withdraw:
      url: http://account.application:8080/withdraw/withdraw
transfer:
  cancel:
      url: http://transfer.application:8080/cancel
      process:
         url: http://transfer.application:8080/processcancel
  confirm:
      url: http://transfer.application:8080/confirm
      process:
         url: http://transfer.application:8080/processconfirm
lra:
  coordinator:
    url: http://otmm-tcs.otmm.svc.cluster.local:9000/api/v1/lra-coordinator