server:
  port: 8081
spring:
  microtx:
    lra:
      coordinator-url: http://localhost:9000/api/v1/lra-coordinator
      #      coordinator-url: http://tmm-app:9000/api/v1/lra-coordinator
      propagation-active: true
      participant-url: http://192.168.205.1:8081
      headers-propagation-prefix: {x-b3-, oracle-tmm-, authorization, refresh-}
account:
  deposit:
      url: http://192.168.205.1:8080/deposit/deposit
  withdraw:
      url: http://192.168.205.1:8080/withdraw/withdraw
transfer:
  cancel:
      url: http://localhost:8081/cancel
      process:
           url: http://192.168.205.1:8081/processcancel
  confirm:
      url: http://localhost:8081/close
      process:
         url: http://192.168.205.1:8081/processclose
