apiVersion: v1
kind: Service
metadata:
  name: account
  labels:
    app: account
    service: account
spec:
  type: ClusterIP
  ports:
    - port: 8080
      name: port
      protocol: TCP
      targetPort: 8080
  selector:
    app: account